---
title: Chris OBrien | Cape Cod web designer, developer and writer.
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    image: 
email: chris@hellodative.com
description: Chris OBrien is a Cape Cod based web designer, developer and writer.
bio: 'Hi, I''m Chris – a designer and writer living on Cape Cod. You can find me elsewhere
  on the interwebs using the links below. '
chris_photo: "/uploads/chris-photo.jpg"
baseurl: 
url: 
twitter_username: tasketernal
github_username: chrisobs13
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
